server:
  port: 8085

lovecode:
  services:
    problem-management:
      baseUrl: http://127.0.0.1:8083

zuul:
  routes:
    problmes:
      path: /api/problems/**
      url: ${lovecode.services.problem-management.baseUrl}
      stripPrefix: false

ribbon:
  eureka:
    enabled: false
