## 服务配置
server:
  port: 8083
  tomcat:
    uri-encoding: utf-8
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jap:
    hibernate:
      ddl-auto: update
    show: true
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: test
